init {
    report("GamePackageManager init started")

    if (version != null && !version.isInstalled) {
        report("Minecraft app not installed, using downloaded game version")

        packageContext = context

        applicationInfo = MinecraftLauncher(context)
            .createFakeApplicationInfo(
                version,
                MinecraftLauncher.MC_PACKAGE_NAME
            )

        nativeLibDir = resolveNativeLibDir()
    } else {
        val packageName = detectGamePackage()
            ?: throw IllegalStateException("Minecraft not found")

        report("Detected Minecraft package: $packageName")

        packageContext = context.createPackageContext(
            packageName,
            Context.CONTEXT_IGNORE_SECURITY or Context.CONTEXT_INCLUDE_CODE
        )

        applicationInfo = packageContext.applicationInfo
        nativeLibDir = resolveNativeLibDir()
    }

    extractLibraries()

    report("Creating AssetManager")
    assetManager = createAssetManager()
    report("AssetManager ready")

    setupSecurityProvider()

    report("GamePackageManager init finished")
}
